server:
  port: 9191
spring:
  datasource:
    url: jdbc:postgresql://172.28.5.194:5432/test?createDatabaseIfNotExist=true
    username: postgres
    password: De$kt0p@2019
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        provider:
          sso-provider:
            user-info-uri: http://localhost:9191/users/me
logging:
  level:
    org:
      hibernate:
        type: trace
